### ISSUE TITLE
[HELP] Creating a Dockerfile & docker-compose

### ISSUE THREAD

**Issue by lnxredir** [hnhx/librex#140]
Hi! Sorry if this is not the right place for this but I've been trying to create a **dockerimage** & **compose** for both myself and the community to use, my knowledge of docker is a bit limited so I got stuck. Here's what I have so far:
**Dockerfile**

```
FROM ajoergensen/nginx-php-fpm:7.4

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive \
  TZ=America/Sao_Paulo \
  apt-get install -y git php php-curl dialog

ENV PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

RUN mkdir /etc/nginx/templates
COPY default.conf.template /etc/nginx/templates
COPY index.html /usr/share/nginx/html/

RUN git clone "https://github.com/hnhx/librex" librex

WORKDIR /librex

EXPOSE 80

RUN mv config.php.example config.php && \
  mv opensearch.xml.example opensearch.xml && \
  sed -i 's/http:\/\/localhost/https:\/\/lbx.frail.duckdns.org/g' opensearch.xml

RUN /etc/init.d/apache2 restart
```

**docker-compose**
```

version: "3.6"

services:
  librex:
    build:
      context: .
    container_name: librex
    ports:
      - "8080:80"
    volumes:
#      - ./default.conf.template:/etc/nginx/templates/
      - ./index.html:/usr/share/nginx/html/
```

The container does run but opens the php test page. I tried a few things but got nowhere. If I made any mistake please let me know. Thanks.

**EDIT**
Forgot to mention a few things, I have the **nginx.conf** and **default.conf.template** in a folder on my server

**Comment by lnxredir** [comment]
Update: New Dockerfile and compose, even with this it still gives me the php test page.

**Dockerfile**
```
FROM ajoergensen/nginx-php-fpm:7.4

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive \
  TZ=America/Sao_Paulo \
  apt-get install -y php php-curl php-xml  nginx git 

ENV PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

RUN echo 'server {\n\
        listen 80;\n\
\n\
        server_name your.domain;\n\
\n\
        root /var/www/html/librex;\n\
        index index.php;\n\
\n\
        location ~ \.php$ {\n\
               include snippets/fastcgi-php.conf;\n\
               fastcgi_pass unix:/run/php/php-fpm.sock;\n\
        }\n\
}\n\'  > default

RUN mkdir /etc/nginx/sites-enabled
RUN mv default  /etc/nginx/sites-enabled/default

RUN git clone "https://github.com/hnhx/librex" librex
WORKDIR /librex

RUN mv config.php.example config.php && \
  mv opensearch.xml.example opensearch.xml && \
  sed -i 's/http:\/\/localhost/https:\/\/lbx.frail.duckdns.org/g' opensearch.xml

EXPOSE 80
RUN /etc/init.d/apache2 restart
```

**docker-compose**
```
version: "3.6"

services:
  librex:
    build:
      context: .
    container_name: librex
    ports:
      - "8025:80"
```
