### ISSUE TITLE
Not able to search torrent

### ISSUE THREAD

**Issue by poudenes** [hnhx/librex#181]
Hello,

I can't search on torrent. Get an error: The host disabled this feature! :C

```
version: "3.9"
services:
  librex:
    image: librex/librex:latest
    container_name: librex
    hostname: librex
    restart: always
    ports:
      - 8245:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumeUSB1/usbshare/docker/librex/nginx:/var/log/nginx
      - /volumeUSB1/usbshare/docker/librex/logs:/var/log/php7
    environment:
      TZ: Europe/Amsterdam
      PUID: 1026
      PGID: 100
      VERSION: docker
      CONFIG_GOOGLE_DOMAIN: com
      CONFIG_GOOGLE_LANGUAGE: en
      CONFIG_WIKIPEDIA_LANGUAGE: en
    networks:
       synology:
         ipv4_address: 172.30.33.122
       
networks:
  synology:
    external: true
```
