### ISSUE TITLE
"Videos" tab won't display any results.

### ISSUE THREAD

**Issue by Qi2nR9uw** [hnhx/librex#182]
This seems to be the case for every instance I try.

**Comment by juniorbotelho** [comment]
The URL that was causing issues has been updated in the `config.php` file, and I have resolved this problem in my Pull Request #179. You can try using Docker instead by following these steps:

```sh
docker run -d \
  --name librex \
  -e TZ="America/New_York" \
  -e CONFIG_GOOGLE_DOMAIN="com" \
  -e CONFIG_GOOGLE_LANGUAGE="en" \
  -e CONFIG_WIKIPEDIA_LANGUAGE="en" \
  -p 8080:8080 \
  librex/librex:latest
```

or

```yml
version: "2.1"
services:
  librex:
    image: librex/librex:latest
    container_name: librex
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ="America/New_York"
      - CONFIG_GOOGLE_DOMAIN="com"
      - CONFIG_GOOGLE_LANGUAGE="en"
      - CONFIG_WIKIPEDIA_LANGUAGE="en"
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./php_logs:/var/log/php7
    restart: unless-stopped
```
